### ISSUE TITLE
Hello, can you add a sequence format?

### ISSUE THREAD

**Issue by UR1666** [WiseGuru/obsidian-automatic-list-styles#1]
Hello, can you add a sequence format?
For example:

-1. Text content
----11.Text content
--------111. Text content
--------112. Text content
----12.Text content
--------121. Text content
--------122. Text content
-2. Text content
----21.Text content
----22.Text content
--------221. Text content
--------222. Text content

Using digits to represent the indentation level, with a maximum of 9 levels.

**Comment by WiseGuru** [comment]
Hey, sorry for the delay; while interesting, I don't think it fits goal of this plugin (especially with only 9 {or 10 if you from 0} levels of depth). Additionally, this plugin uses CSS list styles, and doesn't create its own. https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type. If you haven't already, I recommend forking it and experimenting with it yourself to see if you can get something that suits your needs :)

**Comment by WiseGuru** [comment]
Oops, closed as completed; should be marked as unplanned.
